### ISSUE TITLE
Cannot compare scala.Range

### ISSUE THREAD

**Issue by jhitt-tst** [softwaremill/diffx#126]
```
import com.softwaremill.diffx._

object DiffTest {
  def main(args: Array[String]): Unit = {
    val v1 = Range(0, 1)
    val v2 = Range(0, 1)
    compare(v1, v2)
  }
}

```

Exception in thread "main" java.lang.IllegalArgumentException: The given value `Range 0 until 1` is not a sub type of `TypeName(scala.collection.immutable,Range,List())`
	at magnolia.SealedTrait.rec$1(interface.scala:270)
	at magnolia.SealedTrait.dispatch(interface.scala:272)
	at com.softwaremill.diffx.DiffMagnoliaDerivation

**Comment by ghostbuster91** [comment]
Thanks for reporting, fixed in 0.3.29 :tada:
